basePath: /api/v1
definitions:
  types.LoginPayload:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  types.RegisterPayload:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: backend of the event management app.
  title: Squid Tech API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/types.LoginPayload'
      produces:
      - application/json
      responses: {}
      summary: Login endpoint
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Registration details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/types.RegisterPayload'
      produces:
      - application/json
      responses: {}
      summary: Registration endpoint
      tags:
      - auth
<<<<<<< HEAD
  /profiles/get/:id:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Profile endpoint
      tags:
      - profiles
  /profiles/profile:
=======
  /oauth/google/callback:
>>>>>>> 6f71e80 (implemented google auth)
    get:
      consumes:
      - application/json
      parameters:
<<<<<<< HEAD
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Current Profile endpoint
      tags:
      - profiles
  /profiles/profile/bg:
    patch:
      consumes:
      - form/multipart
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: file.png
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Change Profile Bg Image endpoint
      tags:
      - profiles
  /profiles/profile/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete Profile endpoint
      tags:
      - profiles
  /profiles/profile/pfp:
    patch:
      consumes:
      - form/multipart
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: file.png
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Change Profile Image endpoint
      tags:
      - profiles
  /profiles/profile/update:
    patch:
      consumes:
      - application/json
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: jhon doe
        in: body
        name: name
        schema:
          type: string
      - description: example@gmail.com
        in: body
        name: email
        schema:
          type: string
      - description: im a dev
        in: body
        name: bio
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update Profile endpoint
      tags:
      - profiles
  /profiles/search:
    get:
      consumes:
      - application/json
      parameters:
      - description: example@gmail.com
        in: query
        name: email
        type: string
      - description: aymen charfaoui
        in: query
        name: full_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Search Profile endpoint
      tags:
      - profiles
=======
      - description: The OAuth2 authorization code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Handles Google OAuth2 callback
      tags:
      - auth
  /oauth/google/login:
    get:
      produces:
      - application/json
      responses: {}
      summary: Initiates Google OAuth2 login
      tags:
      - auth
>>>>>>> 6f71e80 (implemented google auth)
swagger: "2.0"
